apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose.exe convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose.exe convert
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - image: bramco/brams6userservice
          name: userservice
          env:
            - name: RabbitMQHostname
              valueFrom:
                secretKeyRef:
                  name: userservicesecret
                  key: RabbitMQHostname
            - name: MongoDBConnectionString
              valueFrom:
                secretKeyRef:
                  name: userservicesecret
                  key: MongoDBConnectionString
            - name: RabbitMQUsername
              valueFrom:
                secretKeyRef:
                  name: userservicesecret
                  key: RabbitMQUsername
            - name: RabbitMQPassword
              valueFrom:
                secretKeyRef:
                  name: userservicesecret
                  key: RabbitMQPassword
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: userservicesecret
                  key: GOOGLE_CLIENT_ID
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources: {}
      hostname: userservice
      restartPolicy: Always
status: {}